name: Sync to Hugging Face
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Verify Secret
        run: |
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "Error: HF_TOKEN is empty. Please add it to your GitHub Secrets."
            exit 1
          fi
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "SyncBot"
          # Using HEAD:refs/heads/main to ensure we push the current commit to the remote main branch
          git push --force https://Dhruvk14:$HF_TOKEN@huggingface.co/spaces/Dhruvk14/Satellite_scheduler_updated HEAD:refs/heads/main
